[package]
name = "reuse"
version = "0.1.0"
authors = ["Arnaud Lefebvre <a.lefebvre@outlook.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
net2 = "0.2"
bytes = "0.5"